Completed css-canvas-medical challenge 1.
AnthonyVNgo/c0322-code-solutions pull request #21
Opened 2022-03-20 07:05 UTC by NV-Anthony

![screencapture-127-0-0-1-5500-css-canvas-medical-index-html-2022-03-20-00_01_58](https://user-images.githubusercontent.com/99709530/159152005-a5c1f1b4-c97c-4726-bb28-068319b073c5.png)

2022-03-21 17:51 UTC, codingcodymiller requested changes
Hey Anthony! The capitalization is wrong on your "Clinicians Prefer Canvas" heading, please revise and submit a new screenshot with your revision.

2022-03-22 19:00 UTC, AnthonyVNgo commented
![screencapture-127-0-0-1-5500-css-canvas-medical-index-html-2022-03-22-11_58_03](https://user-images.githubusercontent.com/99709530/159555881-e7fb2bce-cb8e-4085-8adb-b665deb2609f.png)

2022-03-22 20:15 UTC, codingcodymiller requested changes

2022-03-22 20:15 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +          <div class="column-fourths"></div>
You should never have empty `column` elements in your code. Instead, you should make the `column-fourth` that precedes this element into a `column-half`

2022-03-25 17:49 UTC, codingcodymiller approved these changes
Great work!!

2022-03-30 05:11 UTC, merged