Completed javascript-light-bulb challenge.
AnthonyVNgo/c0322-code-solutions pull request #43
Opened 2022-03-29 20:53 UTC by NV-Anthony

2022-03-29 21:48 UTC, codingcodymiller requested changes
Hey Anthony! Please attach a gif of your functionality in action, then send me a message on Slack once this has been updated.

2022-03-30 04:24 UTC, NV-Anthony commented
![Kapture 2022-03-29 at 21 21 53](https://user-images.githubusercontent.com/99709530/160751077-c85eb0b5-24ec-4af7-b9ee-1a9f9ef1846f.gif)

2022-03-30 17:52 UTC, codingcodymiller requested changes

2022-03-30 17:52 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +  if (button === 0) {
I would suggest using a boolean rather than `0` and `1`

2022-03-30 17:52 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +    // console.log(button);
Please remove all code comments prior to submitting for review.

2022-03-30 17:52 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +    bgOff = document.querySelector('.bg-off');
This is unnecessary. Even if you change classes on the element you selected, the variables holding a DOM element will hold the same element. You can just make one variable to hold the `bulb` element and one variable to hold the `background` element.

2022-03-31 16:12 UTC, codingcodymiller approved these changes
Great work!!

2022-05-02 22:39 UTC, merged