Array manipulation 2
AnthonyVNgo/c0322-code-solutions pull request #59
Opened 2022-04-11 21:03 UTC by NV-Anthony

![image](https://user-images.githubusercontent.com/99709530/162831739-9035589e-901b-4d84-b99e-25ae95c0e365.png)

2022-04-11 23:58 UTC, codingcodymiller requested changes

2022-04-11 23:58 UTC, codingcodymiller commented on array-manipulation-2/src/chunk.js
> +    }
Every block of this conditional has the same work. You can just remove the conditional and do the same work on every iteration.

2022-04-11 23:58 UTC, codingcodymiller commented on array-manipulation-2/src/includes.js
> +  }
You can just `return false` out here, that is the only work you might want to do.

2022-05-15 02:06 UTC, AnthonyVNgo commented
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/99709530/168454169-634c1123-a9ea-4f46-96b8-fb13c1fdd511.png">

2022-05-15 20:55 UTC, thebearingedge approved these changes

2022-05-16 02:04 UTC, merged